language: node_js

node_js:
  - "14"

cache: npm

before_install:
  - npm install -g coveralls

script:
  - npm run build
  - npm run test -- --verbose --collectCoverage
  - cat ./test/coverage/lcov.info | coveralls
