on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: mylesj/node-pnpm-setup@v1
        with:
          node-version: 20
          pnpm-version: 8

      - name: run tests
        run: pnpm test

      - name: collect coverage
        uses: coverallsapp/github-action@v2
        with:
          file: ./test/coverage/lcov.info
